-- ============================================================================
-- Stop the audit log eating the database.
--
-- MEASURED 2026-08-30 on the live DB:
--   database          581 MB  — 116% of the 500 MB free tier
--   audit_log         465 MB  (heap 24 MB, indexes 4 MB, TOAST 438 MB)
--   of which `jobs`   348 MB from 9,394 rows — 97.7% of the whole audit payload
--   `parts`             8 MB from 16,559 rows — the data you would actually audit
--
-- The cause is one column: jobs.meta averages 71 kB, and a sync job is UPDATEd
-- dozens of times as it walks its chunks. Every one of those updates wrote the
-- meta blob into audit_log.
--
-- ⚠ 20260715_audit_diff_only.sql IS ALREADY APPLIED (the live log_audit_event
-- carries its `excl` array). It did not help, because its deny list is
-- description / photos / platform_data and the bloat is `meta`. So this is not
-- "the pending migration finally being run" — it is the fix that one missed.
--
-- Nothing reads any of it. The Activity feed offers Parts and Cars only
-- (src/components/Activity.jsx), so the 348 MB has never been shown to anyone.
--
-- Two changes, smallest first:
--   1. `meta` joins the deny list, so no table can leak a progress blob into
--      the audit trail by having a column with that name.
--   2. The jobs audit trigger is DROPPED. `jobs` is an internal work queue, not
--      business data — there is no story where someone needs to know what a
--      chunk cursor was three weeks ago, and it is regenerated by the next sync
--      anyway. Parts, cars, listings and store_members keep their audit trail
--      untouched: this removes noise, not accountability.
--
-- Idempotent. Apply via the Supabase SQL editor (no PAT required).
-- ============================================================================

-- 1 ── `meta` is never worth auditing on any table -----------------------------
--
-- ⚠ This is the LIVE function read back with pg_get_functiondef, with exactly
-- ONE token changed: 'meta' added to excl. It is deliberately not hand-written.
-- The first attempt at this migration reconstructed the body from the previous
-- migration's prose and got the identity list, the no-op test and the return
-- value all wrong — it returned NEW where the live trigger returns null — which
-- would have quietly changed auditing for parts and cars while claiming to only
-- add a column name.
CREATE OR REPLACE FUNCTION public.log_audit_event()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_old jsonb;
  v_new jsonb;
  d_old jsonb := '{}'::jsonb;
  d_new jsonb := '{}'::jsonb;
  k     text;
  -- bulky / re-creatable — never stored (removed from every snapshot)
  excl  text[] := array['description','photos','platform_data','meta'];
  -- small identifiers kept on every UPDATE row so the feed can label + diff
  ident text[] := array['title','sku','status','make','model','year','deleted_at','platform_sku','name'];
begin
  if TG_OP = 'INSERT' then
    insert into public.audit_log(store_id, table_name, record_id, action, old_data, new_data, changed_by)
    values (NEW.store_id, TG_TABLE_NAME, NEW.id, 'INSERT', null, to_jsonb(NEW) - excl, auth.uid());
    return null;

  elsif TG_OP = 'DELETE' then
    insert into public.audit_log(store_id, table_name, record_id, action, old_data, new_data, changed_by)
    values (OLD.store_id, TG_TABLE_NAME, OLD.id, 'DELETE', to_jsonb(OLD) - excl, null, auth.uid());
    return null;
  end if;

  -- UPDATE: identity fields (both sides, so unchanged ones don't read as changes)
  -- + the columns that genuinely changed, excluding the bulky/re-creatable ones.
  v_old := to_jsonb(OLD);
  v_new := to_jsonb(NEW);

  foreach k in array ident loop
    if v_new ? k then
      d_old := d_old || jsonb_build_object(k, v_old -> k);
      d_new := d_new || jsonb_build_object(k, v_new -> k);
    end if;
  end loop;

  for k in select jsonb_object_keys(v_new) loop
    -- skip excluded columns, and updated_at (redundant with audit_log.changed_at)
    if k <> 'updated_at' and not (k = any(excl))
       and (v_old -> k) is distinct from (v_new -> k) then
      d_old := d_old || jsonb_build_object(k, v_old -> k);
      d_new := d_new || jsonb_build_object(k, v_new -> k);
    end if;
  end loop;

  -- Nothing meaningful changed (only identity present, all equal) → no noise row.
  if d_old = d_new then
    return null;
  end if;

  insert into public.audit_log(store_id, table_name, record_id, action, old_data, new_data, changed_by)
  values (coalesce(NEW.store_id, OLD.store_id), TG_TABLE_NAME, coalesce(NEW.id, OLD.id), 'UPDATE', d_old, d_new, auth.uid());
  return null;
end;
$function$;

-- 2 ── the jobs queue is not audited -------------------------------------------
drop trigger if exists jobs_audit on public.jobs;

-- 3 ── remove what was already written ------------------------------------------
delete from public.audit_log where table_name = 'jobs';

-- 4 ── give the disk back --------------------------------------------------------
-- The DELETE alone frees nothing: the space stays inside audit_log's TOAST as
-- dead tuples and Supabase still bills the table size. VACUUM FULL rewrites the
-- table and returns it. It takes an ACCESS EXCLUSIVE lock — audit writes block
-- for the duration — so run it when a sync is not in flight. On the measured
-- data this rewrites ~10 MB of survivors, so it is seconds, not minutes.
--
-- Cannot run inside a transaction block, so it is left commented: run it as a
-- separate statement, on its own, straight after the delete above.
--
--   vacuum (full, analyze) public.audit_log;
